services:
  minio:
    image: minio/minio:latest
    container_name: cloudstorage-minio

    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Rubysa179596!
      MINIO_SERVER_URL: https://minio-api.motorsights.com
      MINIO_BROWSER_REDIRECT_URL: https://minio-console.motorsights.com

    volumes:
      - /home/msiserver/minio/data:/data

    command: server /data --console-address ":9001"

    restart: unless-stopped

    networks:
      - infra_net

    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
